run:
  timeout: 5m
  modules-download-mode: readonly
  tests: true
  skip-dirs:
    - vendor
    - .git
    - .github
    - .idea
    - bin
    - pkg
    - testdata
  skip-files:
    - ".*_test\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    # Code correctness
    - bodyclose
    - containedctx
    - contextcheck
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - goconst
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nosprintfhostport
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace

  disable-all: true

linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - hugeParam
      - rangeValCopy
  govet:
    check-shadowing: true
  gosec:
    excludes:
      - G104 # Errors unhandled (already covered by errcheck)
      - G307 # Deferring unsafe Close() calls
  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
