name: CI

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "1.23.4"
      - run: go clean -modcache
      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{runner.os}}-go-${{hashFiles('**/go.sum')}}
          restore-keys: |
            ${{runner.os}}-go-
      - run: go mod download

  unit-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "1.23.4"
      - run: |
          go test -coverprofile=unit-coverage.txt -covermode=atomic \
          -coverpkg=./cmd/...,./internal/...,./pkg/storage/...,./middleware/... \
          $(go list -f '{{.Dir}}' ./... | xargs -I {} find {} -name "*_test.go" ! -name "*_integration_test.go" | xargs dirname | sort -u)

      - uses: codecov/codecov-action@v5
        with:
          files: unit-coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}

  integration-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "1.23.4"
      - run: |
          go test -coverprofile=integration-coverage.txt -covermode=atomic \
          -coverpkg=./cmd/...,./internal/...,./pkg/storage/...,./middleware/... \
          $(go list -f '{{.Dir}}' ./... | xargs -I {} find {} -name "*_integration_test.go" | xargs dirname | sort -u)
      - uses: codecov/codecov-action@v5
        with:
          files: integration-coverage.txt
          token: ${{secrets.CODECOV_TOKEN}}
